### ISSUE TITLE
TDown 下载

### ISSUE THREAD

**Issue by FreeVB** [Haku-Men/HttpLib#2]
TDown 下载这个下载测试为什么下了100多M还没完成？这个库下载后不是很小吗？
而且最后调用CombineMultipleFilesIntoSingleFile时发生错误。
qq:289778005

**Comment by FreeVB** [comment]
而且下载进度、剩余时间、完成时间也没有显示内容。

**Comment by Eviav** [comment]
你下载什么东西呢，git都是不返回文件长度动态下载是没有办法计算进度的，用正常的文件下载地址

**Comment by FreeVB** [comment]
就是测试项目，没有修改东西。

**Comment by Eviav** [comment]
我只能说是正常的，你给一个带长度的http下载地址就好了，什么都不改，是下载动态生成的源码zip，没有长度是无法计算进度和时间的

**Comment by FreeVB** [comment]
但没有下载成功，最后调用CombineMultipleFilesIntoSingleFile时发生错误。
